export const SET_BOOKS = 'SET_BOOKS';
export const SET_CATEGORY = 'SET_CATEGORY';
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const TOGGLE_SEARCH = 'TOGGLE_SEARCH';
export const TOGGLE_THEME = 'TOGGLE_THEME';