import Head from 'next/head';
import { GlobalStyle } from '../styles/GlobalStyle.js';
import 'bootstrap/dist/css/bootstrap.css';
import { Provider } from 'react-redux';
import store from '../Redux/Store.js';
import Router, { useRouter } from 'next/router';
import NProgress from 'nprogress';
import 'nprogress/nprogress.css';

Router.events.on('routeChangeStart', () => NProgress.start());
Router.events.on('routeChangeComplete', () => NProgress.done());
Router.events.on('routeChangeError', () => NProgress.done());
function MyApp({ Component, pageProps }) {
  return (
    <div>
      <Head>
        <title>BookShop</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://blogs.slj.com/afuse8production/files/2020/10/GreenEarthBookAward-500x500.png"
        />
        <script src="//code-eu1.jivosite.com/widget/mrpq5BWPSs" async></script>
      </Head>
      <GlobalStyle />
      <Provider store={store}>
        <Component {...pageProps} />
      </Provider>
    </div>
  );
}

export default MyApp;
